name: Docker Image CI

env:
  IMAGE_NAME: ${{ github.repository_owner }}
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set image name to lowercase
      run: echo "IMAGE_NAME_LC=${IMAGE_NAME,,}" >> $GITHUB_ENV
      
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Cache Cargo registry and git sources 
      uses: actions/cache@v4 
      with: 
        path: | 
          ~/.cargo/registry 
          ~/.cargo/git 
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }} 
        restore-keys: | 
            ${{ runner.os }}-cargo-
        
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image (no buildx)
      run: |
        docker build -t ghcr.io/${{ env.IMAGE_NAME_LC }}/stoatchat:latest .

    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ env.IMAGE_NAME_LC }}/stoatchat:latest
